apiVersion: v1
data:
  config.yaml: |-
    redis:
      address: "redis-svc"
      port: "6379"
      password: ""
      db: "0"

    rabbitmq:
      login: "guest"
      password: "guest"
      address: "rabbitmq"
      port: "5672"
      exchangename: "events"
      exchangetype: "topic"
      queuename: "test"

    poster:
      port: "6666"
      function: ""

    explorer:
      port: "80"
      function: ""
kind: ConfigMap
metadata:
  name: goingtorest-config
  namespace: goingtorest
